[colors.primary]
background = "0x1a0a02" # Casi negro puro para que el naranja flote
foreground = "0xff8700" # El naranja "NERV" clásico

[colors.normal]
black   = "0x1c1c1c"
red     = "0xaf0000" # Un rojo oscuro sangre
green   = "0x5f8700" # Un verde oliva táctico
yellow  = "0xaf8700" # Un oro viejo
blue    = "0xff8700" # Naranja (Mantenemos el monocromatismo)
magenta = "0xaf5f00" # Naranja quemado
cyan    = "0xffaf00" # Naranja claro para links
white   = "0xbcbcbc"

[colors.bright]
black   = "0x444444"
red     = "0xd70000"
green   = "0x87af00"
yellow  = "0xffaf00" # Amarillo ámbar brillante
blue    = "0xff8700"
magenta = "0xd78700"
cyan    = "0xffd700" # El color para lo que tiene que resaltar sí o sí
white   = "0xffffff"


[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 1
# [selection]
# save_to_clipboard = true
